# Generated by Django 4.1.4 on 2023-04-06 09:47

from django.db import migrations, models
import django.db.models.deletion
import users.fchecker


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('Website', models.CharField(max_length=50)),
                ('Type', models.CharField(choices=[('TECH', 'Techanical'), ('NOTECH', 'Non-Techanical'), ('TEL', 'Telecom'), ('MFN', 'Manufacturing'), ('RTL', 'Retail'), ('STP', 'StartUp')], max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=13)),
                ('Postal_Code', models.IntegerField()),
                ('Address', models.TextField(max_length=250)),
                ('Is_Created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Roll', models.SmallIntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('TRAIN', 'Training'), ('TRAINED', 'Trained'), ('PLACED', 'Placed')], max_length=7)),
                ('Mobile', models.CharField(max_length=13)),
                ('Graduation_Year', models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)])),
                ('Course', models.CharField(blank=True, choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech')], max_length=10)),
                ('Branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')], max_length=3)),
                ('Resume', models.FileField(upload_to='media/resume', validators=[users.fchecker.FileExtensionValidator(allowed_extensions=['pdf'], max_file_size=2621440)])),
                ('Is_Created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')], default='CSE', max_length=3)),
                ('Eligiblity', models.CharField(choices=[('BTECHGRAD', 'B.Tech Graduate'), ('MTECHGRAD', 'M.Tech Graduate'), ('BOTH', 'Both')], max_length=15)),
                ('Salary', models.CharField(help_text='in LPA', max_length=14)),
                ('Responsiblities', models.TextField(max_length=100)),
                ('Benefits', models.TextField(max_length=100)),
                ('Starting_date', models.DateField()),
                ('Location', models.TextField(max_length=50)),
                ('Experience', models.TextField(help_text='Enter any special requirments such as year of experience, etc')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
    ]
