# Generated by Django 4.1.4 on 2023-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_offer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
